// Phase 17.7: the lines players read most. A night at the fire (`lot.sit`) said by whoever's
// there, and a send said back by whoever was with you (ambient.ts). v0.956's campfire outcomes
// came round about seven times each by day 100 (docs/audit/social.md §5.2); these are sized
// against it. The fire's are in the order they open (FIRE): the later ones belong to people
// who've known you a while.

export const FIRE_LINES: Record<string, string[]> = {
  hazel: [
    'Hazel tells you about the winter the Lot froze solid and everyone slept in one van. She won’t say whose.',
    'Hazel pokes the fire and says it’s the best thing she’s done all day. It might be.',
    'Hazel reads out the forecast like it’s a horoscope. Tomorrow: a sense of unfinished business.',
    'Hazel asks what you’d climb if your hands didn’t hurt. You both know the answer.',
    'Hazel says she used to want to climb hard. Now she wants to climb tomorrow. She thinks that’s harder.',
    'Hazel hums something tuneless and lets the silence do the rest.',
    'Hazel says the trick to the Lot is never owning anything you’d miss. She owns nine mugs.',
    'Hazel shows you a scar on her knuckle and won’t tell you how. "Granite," is all she says.',
    'Hazel tells you which van has the best stove and which one has the best neighbor. Hers, twice.',
    'Hazel says the best day climbing she ever had, she didn’t send anything. She doesn’t explain.',
    'Hazel throws the last of the coffee on the fire. It hisses. "Bedtime," it seems to say.',
    'Hazel says the valley gets smaller every year and the climbing gets bigger. Both are true.',
    'Hazel watches the sparks go up and counts them, out loud, till she loses track at eleven.',
    'Hazel says she once tried to leave the Lot. She got as far as the diner and had pie instead.',
    'Hazel talks about rope like other people talk about dogs. She’s had seven. She remembers them all.',
    'Hazel asks how your skin is, then looks at your hands and answers for you.',
    'Hazel tells the one about the ranger, the goat and the portaledge. It doesn’t get better. It gets longer.',
    'Hazel says nothing for a long time, then: "Good day." It was.',
    'Hazel says she has a theory about chalk brands. She does not have a theory about chalk brands.',
    'Hazel says if you want to know a climber, watch them walk down from a route they didn’t send.',
    'Hazel says the coffee’s better at night. It isn’t. It’s just quieter.',
    'Hazel says the Lot has one rule nobody wrote down: you don’t ask anyone why they’re here.',
    'Hazel says her first rack cost more than her van. She stands by it.',
    'Hazel says you climb like someone who’s about to be good at it. She means it kindly. Mostly.',
    'Hazel says you’ve been here long enough to have opinions about the dumpster schedule. You do.',
    'Hazel asks where you’d go if the Lot closed tomorrow. Neither of you has an answer you like.',
    'Hazel says she can tell the season by which vans leave first. The ones with kids, then the ones with jobs.',
    'Hazel teaches you a knot that’s no use for climbing. "For the tarp," she says. It is good for the tarp.',
    'Hazel says she nearly bought a house once. She went to see it and stood in the kitchen and felt walls.',
    'Hazel says the first winter is the one that sorts people. You’re still here. She doesn’t say more.',
    'Hazel mends a sock by the fire with the concentration of someone onsighting.',
    'Hazel says her mother still asks when she’s getting a real job. Her mother is eighty. Hazel is fifty-one.',
    'Hazel says the trick with a hard route is to stop wanting it and keep trying it. She’s working on the first part.',
    'Hazel tells you about a partner she had for nine years who moved to the coast. They send postcards. Neither writes much.',
    'Hazel says you’ve started walking like a local: slowly, and only once you’ve checked the sky.',
    'Hazel says the Lot was quieter before. Then she admits she was the loud one.',
    'Hazel asks if you miss anything from before. She means it. You think about it longer than you expect.',
    'Hazel says you should never trust a climber who says they’re just going to have a look.',
    'Hazel says she keeps a list of everyone who’s passed through. It’s long. You’re on it twice: arriving, and staying.',
    'Hazel makes toast on a stick and it’s the best toast either of you has had.',
    'Hazel says there’s a version of her who never came here. She sometimes wonders how that one’s doing. Fine, probably. Bored.',
    'Hazel says you’ve got good at the quiet. She means the fire, and the waiting on bad days.',
    'Hazel says her knees forecast rain better than the radio. Tonight they say Thursday.',
    'Hazel says the first thing she ever led was too hard and she cried at the second bolt. She’d do it again.',
    'Hazel asks what grade you think you’ll stop at. You say you won’t. She laughs, then stops, then says, "Good."',
    'Hazel tells you which locals have quietly started asking her about you. She won’t say what they asked.',
    'Hazel says she doesn’t do resolutions. She does a list of routes and crosses one off every few years.',
    'Hazel says the Lot has seen people come in with everything and leave with a duffel. It’s seen the other way too, once.',
    'Hazel says she’s happier now than at thirty. She says it like she’s checking it’s still true. It is.',
    'Hazel says you’ll know you’ve been here too long when the new kids ask you for beta. Then she points out one already has.',
    'Hazel warms her hands and says, without looking, that she’s glad you parked where you parked.',
    'Hazel says some nights the fire’s just a fire, and that’s the best kind.',
    'Hazel says she’s stopped counting the years here. You notice she still knows the number.',
    'Hazel says if you ever leave, leave in the spring. Nobody should drive off from a fire in winter.',
    'Hazel asks you to tell her about your first day at the Lot. She remembers it differently. Her version is kinder.',
  ],
  sage: [
    'Sage draws a topo in the dirt with a stick and makes you guess the line. You guess wrong. She’s pleased.',
    'Sage reads a guidebook by firelight, correcting the grades in pencil.',
    'Sage says the hardest move on any route is the first one you decide not to try.',
    'Sage asks what you were thinking on the crux. You weren’t. She says that’s the problem, and the answer.',
    'Sage tells you about a route in the Bugaboos that took her six days to read and an hour to climb.',
    'Sage says she likes the fire because nobody expects her to talk at it.',
    'Sage says she doesn’t believe in projects. She believes in lines she hasn’t understood yet.',
    'Sage lists every route she’s fallen off this year. It takes a while. She seems happy about it.',
    'Sage says beta is a gift you have to unwrap yourself. Then she gives you the beta anyway.',
    'Sage watches the fire like it’s a sequence she nearly has.',
    'Sage says the best climbers she knows are bored by easy routes and patient with hard ones.',
    'Sage asks if you’ve noticed your left foot does all the work. You hadn’t. Now you can’t stop.',
    'Sage says the rock doesn’t care how you feel about it. She finds that restful.',
    'Sage tells you about the first route she ever cried on. She was thirty. She’d led it.',
    'Sage sketches your project from memory, every hold, and gets one wrong on purpose to see if you notice.',
    'Sage says guiding taught her to watch people’s hands, not their faces. Hands don’t pretend.',
    'Sage says the problem with talent is it lets you skip the bit where you learn to read.',
    'Sage asks what scares you up there. You tell her. She nods like it’s a reasonable fear, which helps.',
    'Sage says she stopped counting her sends years ago. She still counts her falls. They tell her more.',
    'Sage says the best beta she ever got was from a seven-year-old who couldn’t reach the holds she used.',
    'Sage tells you she nearly quit once, at the top of a route, because it was finished and she felt nothing.',
    'Sage reads the weather off the clouds and is right, which is annoying.',
    'Sage says she likes climbing with you because you ask the questions after, not during.',
    'Sage says every crag has one route nobody likes and everybody climbs. She’s fond of those.',
    'Sage says she used to think the summit was the point. Now she thinks the walk-off is.',
    'Sage tells you about a partner who never said "take" in ten years. "He fell a lot," she says. "Quietly."',
    'Sage asks which route you’d save, if you could only keep one. She already knows hers.',
    'Sage says you climb differently now. She doesn’t say better. She means it.',
    'Sage says the fire’s like a crux: you look at it long enough and it stops being scary and starts being interesting.',
    'Sage says nothing for a while, then tells you which line on the wall she thinks is yours. You hadn’t seen it.',
  ],
  frank: [
    'Frank fixes a zip on your jacket without being asked and without looking at it.',
    'Frank tells you about every engine he’s ever had, in order, and which one he misses.',
    'Frank says he once drove to the coast for a sandwich. He’s still not sure it was worth it. He’d do it again.',
    'Frank says a van is just a tent that’s decided to be stubborn.',
    'Frank whittles something that might be a bird. It might be a wrench.',
    'Frank says the road teaches you two things: when to stop, and that you won’t.',
    'Frank offers you something from a jar. It’s pickled. You don’t ask what.',
    'Frank says nine years ago he had a plan. He describes it. It sounds like now.',
    'Frank tells you the trick to a cold night is wool, soup, and not thinking about it.',
    'Frank says climbers are the only people he’s met who pay to be tired.',
    'Frank goes quiet, then says the stars are better out here than anywhere he’s parked.',
    'Frank says he’s never climbed. He watches you like he might start.',
    'Frank says he can fix anything with a wire hanger, except a marriage. He tried.',
    'Frank says he’s seen this valley from a hundred angles and never once from the top of anything.',
    'Frank teaches you to hear a bad bearing from fifty feet. You can’t stop hearing them now.',
    'Frank says the trouble with settling down is you have to pick a place to do it in.',
    'Frank reads the paper three days late and argues with it anyway.',
    'Frank tells you about a dog he had who rode shotgun for eleven years and never once looked at the view.',
    'Frank says he has a sister in Ohio who sends him socks. He’s wearing three pairs of them.',
    'Frank says he used to think the road would run out. It doesn’t. You do, a bit.',
    'Frank asks what a crimp is. You show him. He tries it on the cooler. He doesn’t ask again.',
    'Frank says people at the Lot talk about the weather the way his dad talked about the war.',
    'Frank says he’s parked by worse people than you. He means it as the highest thing he says.',
    'Frank says a man should have one good knife, one good pan and one good reason to get up. He’s got two of three.',
    'Frank says he doesn’t miss anything. Then he names his old truck, the blue one, and goes quiet.',
    'Frank tells you he watched you on the wall today, from the road, and had to stop the truck.',
  ],
};

// Said when a line goes, by whoever was with you for it.
export const SEND_CHEERS: Record<string, string[]> = {
  hazel: [
    'Hazel lowers you off and says, "Well, that’s that, then," which is high praise.',
    '"Told you," Hazel says. She didn’t, but she was thinking it.',
    'Hazel takes a photo of you at the anchor and gets mostly sky.',
    'Hazel says the clipping was ugly and the climbing was lovely.',
    'Hazel claps exactly twice.',
    '"Good," Hazel says. "Now do it again so I believe it."',
    'Hazel says she’ll tell everyone at the Lot. She tells one person. It’s enough.',
    'Hazel hands you water before you’ve untied. She knew.',
  ],
  sage: [
    'Sage nods like you’ve answered a question correctly.',
    '"You read it," Sage says. "That’s the bit that counts."',
    'Sage says your feet were perfect on the crux. She saves "perfect" for very few things.',
    'Sage writes it in her notebook. You don’t know what she wrote.',
    'Sage smiles the small smile that means you surprised her.',
    '"Next," Sage says, and points at something harder.',
    'Sage says you climbed it like water. You’ll take that.',
    'Sage says nothing at all, which from her is a standing ovation.',
  ],
  mara: [
    '"Fine," Mara says. You’ve learned that’s a lot.',
    'Mara says don’t celebrate. Then she does, a bit.',
    '"About time," Mara says, and means it fondly.',
    'Mara watched the whole thing and only winced once.',
    'Mara says your crimping is finally less embarrassing.',
    '"That was clean," Mara says, and then, "mostly."',
    'Mara nods once. You’ll remember it for a week.',
    'Mara says the next one up is harder. She says it like a gift.',
  ],
  rico: [
    'Rico yells loud enough to scare the birds off the rim.',
    '"SEND," Rico shouts, at nobody, at everyone.',
    'Rico films it and narrates it like a nature documentary.',
    'Rico lifts you off the pads and puts you down again, for no reason.',
    'Rico says that’s going in the highlight reel. He doesn’t have a highlight reel.',
    '"Horrible," Rico says, delighted. "You loved it."',
    'Rico high-fives you so hard your hand stings for an hour.',
    'Rico tells three strangers what you just did. They’re polite about it.',
  ],
  tam: [
    'Tam says, "Good," and then, "now rest." He means both.',
    'Tam says you didn’t hurry, and that’s why.',
    'Tam watched every move and says you breathed in the right places.',
    'Tam pours you tea from his thermos without a word.',
    'Tam says he did that route in another life. He says you did it better.',
    'Tam says nothing, but he coils the rope for you, which he never does.',
    'Tam says the top is the least interesting part. Then asks what the view was like.',
    'Tam says you climb like you mean to be doing it a long time. He likes that.',
  ],
  dex: [
    'Dex says, "Lucky." He doesn’t think it was luck.',
    'Dex pretends to be looking at something else. He wasn’t.',
    '"I did that faster," Dex says. He didn’t.',
    'Dex nods, the smallest nod there is.',
    'Dex says it’s soft for the grade. He tried it twice last week.',
    '"Not bad," Dex says, which costs him something every time.',
    'Dex goes straight to his own project, harder, which is its own kind of compliment.',
    'Dex says, "Next one," like it’s a dare. It is.',
  ],
};

// A night on a big wall's portaledge, said by whoever's up there with you (Phase 24's
// expeditions): the longest stretch without a fire, so it gets its own, heard in order.
export const LEDGE_LINES: Record<string, string[]> = {
  hazel: [
    'Hazel makes coffee on the hanging stove like it’s any other morning. It isn’t. It’s the best one.',
    'Hazel says she’s never slept well on a ledge and never wanted to be anywhere else.',
    'Hazel points out the Lot’s lights, or somewhere’s. "Close enough," she says.',
    'Hazel tells you the trick to a portaledge is not to think about the word "hanging".',
    'Hazel hums the same tuneless thing she hums at the fire. Up here it sounds like a song.',
    'Hazel says she did her first wall at twenty-six, and cried on the summit, and won’t be doing that again. She might.',
    'Hazel clips her mug to the anchor before she drinks from it. "Lost three," she says.',
    'Hazel says goodnight to the haul bag. You hear yourself say it too.',
    'Hazel says the wall makes the Lot look small, and the Lot makes the wall look possible.',
    'Hazel shares the last of the good chocolate exactly in half and watches you check.',
    'Hazel asks if you’re glad you came. You are. She says she knew, she just likes hearing it.',
    'Hazel says when she’s old she wants to remember nights like this one, not the sends.',
    'Hazel says she’s been up here in her head every night for a year. It’s colder than she pictured.',
    'Hazel tells you the one about the ranger and the goat again. It’s better on a ledge.',
    'Hazel says the Lot would laugh to see her now. Then she says they’d be jealous, and means it.',
    'Hazel says she used to think walls were for other people. She’s still not sure she isn’t one.',
    'Hazel wraps her hands round the mug and says this is what the coffee was for, all those years.',
    'Hazel counts the pitches left on her fingers, then stops counting and looks at the moon.',
    'Hazel says if she falls asleep first, wake her for the sunrise. She’s awake before you.',
    'Hazel says she’s glad it was you who asked. She says it to the wall, which is easier.',
  ],
  sage: [
    'Sage reads tomorrow’s pitches off the topo by headlamp, twice, then puts it away and looks at the real thing.',
    'Sage says walls are just a lot of single pitches that won’t let you go home.',
    'Sage sleeps the second she lies down. You hear her breathing slow over the wind.',
    'Sage says the exposure stops being frightening on the third day and starts being company.',
    'Sage tells you which pitch she thinks will be the crux. She’s wrong for once, and delighted.',
    'Sage watches the light go off the far wall and says nothing at all for an hour.',
    'Sage says the best part of a wall is that there’s only one thing to do tomorrow.',
    'Sage asks how your hands are, then tapes them for you without asking again.',
    'Sage says her first wall she didn’t sleep for four nights. "You’ll sleep," she says. You do.',
    'Sage lists the pitches you’ve climbed so far, in order, like a poem she’s learning.',
    'Sage says the haul bag is the real crux of any wall, and kicks it, gently.',
    'Sage says you lead differently up here: slower, and better. She doesn’t say better twice.',
    'Sage says she guided this wall for years and never once saw it like this, from the inside of a week.',
    'Sage tells you the wall has a rhythm and you’ve found it. You didn’t know you had.',
    'Sage clips your helmet to the anchor before you can drop it. She doesn’t mention it.',
    'Sage says the best partners are the ones you can be quiet with for a whole day. You have been.',
    'Sage draws tomorrow’s pitch on the back of your hand with a pen. It washes off by noon.',
    'Sage says she’s stopped being scared of falling and started being scared of finishing.',
    'Sage asks what you’ll climb when you’re down. You both laugh, because you know.',
    'Sage says goodnight, then, after a long time, "Thanks for bringing me." You didn’t. She came.',
  ],
  mara: [
    'Mara eats exactly her ration, folds the wrapper and puts it away. She doesn’t believe in treats on a wall.',
    'Mara says it’s going fine. From her, that’s a week of reassurance.',
    'Mara checks the anchor twice before sleep. Then once more. Then sleeps.',
    'Mara tells you about the wall in Patagonia that sent her home. She tells it like a draw.',
    'Mara says don’t look down. You both do. She says, "Fine. Look."',
    'Mara asks if you’re scared. You say yes. She says, "Good. Keep it."',
    'Mara says the hardest part of a wall is the bit where you could still go down.',
    'Mara says goodnight like it’s an order, and you sleep like it was one.',
    'Mara says this is the first wall she’s done with someone she didn’t want to push off it.',
    'Mara files her nails by headlamp. "Crimps," she says, before you can ask.',
    'Mara says the summit doesn’t count till you’re back on the ground. Then it barely counts.',
    'Mara watches the storm come in and says, flatly, that she’s seen worse. You believe her.',
    'Mara says she’s never told anyone why she climbs walls. She doesn’t tell you either. She nearly does.',
    'Mara racks the gear for tomorrow in the dark, by feel, in order, and it’s right.',
    'Mara says the rock up here is honest. "It lets you know," she says, and that’s all.',
    'Mara shares her chocolate. She says it’s a mistake. She shares the next one too.',
    'Mara says the wind sounds like her old coach. "Again," it says. "Again."',
    'Mara says she climbs better with you below her. She says it like a weather report.',
    'Mara lies awake and says, quietly, that she used to do these alone. She doesn’t say why she stopped.',
    'Mara says you can celebrate when you’re down. Then, after a while: "A bit now. Fine."',
  ],
  rico: [
    'Rico shouts goodnight into the dark and the wall shouts it back. He is thrilled.',
    'Rico eats a whole day’s food and claims it was a strategy.',
    'Rico tells a story so loud you worry for the people on the next wall.',
    'Rico says this is the best night of his life. He said that last night.',
    'Rico wants to name the ledge. He names it after you.',
    'Rico falls asleep mid-sentence. The sentence was about not being tired.',
    'Rico says when he gets down he’s eating everything in the valley. He lists it. It takes an hour.',
    'Rico goes quiet for once and says the stars up here are something else. They are.',
    'Rico tries to cook pasta on the hanging stove. It goes about as well as you’d think.',
    'Rico says he’s writing a song about the wall. It has one line and he sings it all night.',
    'Rico admits, very quietly, that he’s scared of the dark. He says it to the stars.',
    'Rico says you’re the best partner he’s had. He said it to the last one. He means it more.',
    'Rico teaches the haul bag a trick. It doesn’t learn. He’s proud of it anyway.',
    'Rico says he’s going to tell everyone about this. He practices telling it to you.',
    'Rico runs out of jokes on the fourth night and starts telling the truth. It’s better.',
    'Rico says his mom thinks he’s at a festival. Technically he’s at the biggest one there is.',
    'Rico sings to the storm until it moves on. He says it worked. You can’t prove it didn’t.',
    'Rico says the Cave seems a long way off from up here. He says he misses it. He doesn’t.',
    'Rico eats his last bar and gives you half before you can say no.',
    'Rico says, nearly asleep, that he never thought he’d get to do this. Then he’s snoring.',
  ],
  tam: [
    'Tam brews tea in the dark and passes you a cup without a word. It is very good tea.',
    'Tam says he slept on this wall forty years ago. The ledge was worse. The view wasn’t.',
    'Tam says walls teach patience to people who didn’t want to learn it. He looks at you kindly.',
    'Tam tells you the name of every star he knows, and makes up the ones he doesn’t.',
    'Tam says the rock’s older than every worry you brought up here. It helps.',
    'Tam says goodnight to the valley, the wall, the rope and you, in that order.',
    'Tam says this might be his last wall. He says it lightly, and lets you hear it.',
    'Tam lies awake and says, to nobody, "Still good." You think he means the night.',
    'Tam says the best thing about a wall is that worry can’t climb it.',
    'Tam tells you about his first partner, gone now, who taught him to tie in with his eyes shut.',
    'Tam says young climbers look up and old ones look out. He’s looking out.',
    'Tam says, before he sleeps, that he’s glad of the company. He says it like it costs nothing.',
    'Tam says the wall hasn’t changed in forty years. He has. He says it’s the better deal.',
    'Tam teaches you to coil the rope the old way. It’s slower, and you’ll do it forever now.',
    'Tam says his knees will hate him tomorrow. He says it like he’s looking forward to the argument.',
    'Tam tells you about the night he spent on this ledge in a storm, with a man who never climbed again.',
    'Tam says you don’t need to fill silences up here. He fills one, kindly, with nothing.',
    'Tam watches you sleep for a while, he tells you in the morning, to check you were breathing right.',
    'Tam says this is the view he’d choose, if anyone asked him to choose one.',
    'Tam says goodnight and then, "Thank you for bringing an old man up a wall." You both know who brought who.',
  ],
  dex: [
    'Dex says he’s not scared. He checks his knot four times saying it.',
    'Dex admits, around midnight, that he’s glad it’s you up here and not someone faster.',
    'Dex races you to set up the ledge. He wins, and it’s upside down.',
    'Dex says when he leads tomorrow he’ll be quicker than you. He is, a bit.',
    'Dex goes quiet and says he’s never been this high off anything. Then: "Don’t tell anyone."',
    'Dex offers you the last of his chocolate, which is worth more than his rack up here.',
    'Dex says walls are overrated. He says it with his face pressed to the view.',
    'Dex says goodnight first, for once, and means it.',
    'Dex says he’s been training for walls. He has not been training for walls.',
    'Dex asks what the plan is if it storms. You tell him. He nods like he had the same plan.',
    'Dex says up here nobody can see his tick list. He seems lighter for it.',
    'Dex falls asleep holding the topo. You take it off him before the wind does.',
  ],
};
